name: notion-backup-docker-run

on:
  # adds a "run workflow" button to the page
  # workflow_dispatch:
  workflow_dispatch:
  schedule:
    - cron: '0 6 */3 * *'

# See https://github.com/marketplace/actions/docker-run-step
# See https://github.com/addnab/docker-run-action

jobs:
  run-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Decodes Gdrive Secret
        run: |
          echo $GDRIVE_KEYS_BASE64 | base64 -d > gdrive_creds.json
        env:
          GDRIVE_KEYS_BASE64: ${{ secrets.GOOGLE_DRIVE_SERVICE_ACCOUNT_SECRET_JSON_BASE64 }}
      
      - uses: kohlerdominik/docker-run-action@v1
        with:
          # public, private or local image
          image: ghcr.io/jckleiner/notion-backup
          volumes: ${{ github.workspace }}:/workspace
          # pass or create environment variables
          environment: |
            NOTION_SPACE_ID=${{ secrets.NOTION_SPACE_ID }}
            NOTION_EMAIL=${{ secrets.NOTION_EMAIL }}
            NOTION_PASSWORD=${{ secrets.NOTION_PASSWORD }}
            
            GOOGLE_DRIVE_ROOT_FOLDER_ID=${{ secrets.GOOGLE_DRIVE_ROOT_FOLDER_ID }}
            GOOGLE_DRIVE_SERVICE_ACCOUNT=${{ secrets.GOOGLE_DRIVE_SERVICE_ACCOUNT }}
            GOOGLE_DRIVE_SERVICE_ACCOUNT_SECRET_FILE_PATH=/workspace/gdrive_creds.json
            
            DROPBOX_ACCESS_TOKEN=${{ secrets.DROPBOX_ACCESS_TOKEN }}
            
            NEXTCLOUD_EMAIL=${{ secrets.NEXTCLOUD_EMAIL }}
            NEXTCLOUD_PASSWORD=${{ secrets.NEXTCLOUD_PASSWORD }}
            NEXTCLOUD_WEBDAV_URL=${{ secrets.NEXTCLOUD_WEBDAV_URL }}
            
            PCLOUD_ACCESS_TOKEN=${{ secrets.PCLOUD_ACCESS_TOKEN }}
            PCLOUD_API_HOST=${{ secrets.PCLOUD_API_HOST }}
            PCLOUD_FOLDER_ID=${{ secrets.PCLOUD_FOLDER_ID }}

          # run is required: "Error: Input required and not supplied: run"
          run: |
            uname -a



